### ISSUE TITLE
To up ammo

### ISSUE THREAD

**Issue by profjahier** [pddring/cpu-battle-tank#15]
Hello,
I think driving on an ITEM_TYPE_AMMO doesn't actually top up the ammo.
I suggest adding :
					**if (task[2] == bt.ITEM_TYPE_AMMO) {
					// top up ammo
						var tank = bt.getTankByCoordinates(x, y);
						if(tank) {
							tank.ammo += 10;
							if(tank.ammo > tank.maxAmmo)
								tank.ammo = tank.maxAmmo;
						}
					}**
after line 234 (batlletanks.js)

**Comment by pddring** [comment]
Thank you! I wasn't aware anyone had got as far as using ammo powerups - that's impressive :)
